/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kboxviewer;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Glenn Dimaliwat
 */
public class KBOXJFrame extends javax.swing.JFrame {

    private static DefaultTableModel tableModel;
    private DefaultTableModel model;
    private static final String hostname = "172.18.200.153";
    private static final String port = "3306";        
    private String selectedTicketNumber = "";
    private String searchKey = "";
    private boolean repeatSearch = false;
    
    /**
     * Creates new form KBOXJFrame
     */
    public KBOXJFrame() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KBOX Viewer");
        setPreferredSize(new java.awt.Dimension(1175, 429));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setLabel("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Path to Tickets File:");

        jTextField1.setText("C:/kbox.txt");

        jButton2.setText("Edit File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Cell mode");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Go to Ticket URL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jToggleButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setMnemonic('F');
        jMenu2.setText("File");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem6.setMnemonic('r');
        jMenuItem6.setLabel("Refresh");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setMnemonic('C');
        jMenuItem7.setText("Cell mode");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem1.setMnemonic('x');
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu1.setMnemonic('S');
        jMenu1.setText("Search");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setMnemonic('F');
        jMenuItem4.setText("Find");
        jMenuItem4.setToolTipText("");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem5.setText("Find Next");
        jMenuItem5.setToolTipText("N");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu3.setMnemonic('H');
        jMenu3.setText("Help");
        jMenu3.setToolTipText("");

        jMenuItem3.setMnemonic('U');
        jMenuItem3.setText("How to use this App");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem2.setMnemonic('b');
        jMenuItem2.setText("About");
        jMenuItem2.setToolTipText("");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1277, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initCustomComponents() {
        tableModel = new DefaultTableModel(new Object[] { "TICKET ID", "TITLE", "CREATED", "MODIFIED", "DUE DATE", "REQUEST TYPE", "CLASSIFICATION", "OWNER", "STATUS", "REASON FOR PENDING" }, 0);
        jTable1.setModel(tableModel);  
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        
        // set preferred column widths
        TableColumn a;
        a = jTable1.getColumnModel().getColumn(0);
        a.setPreferredWidth(60);
        a.setCellRenderer(new CustomTableCellRenderer());
        a = jTable1.getColumnModel().getColumn(1);
        a.setPreferredWidth(200);
        a.setCellRenderer(new CustomTableCellRenderer());
        a = jTable1.getColumnModel().getColumn(2);
        a.setPreferredWidth(100);
        a.setCellRenderer(new CustomTableCellRenderer());
        a = jTable1.getColumnModel().getColumn(3);
        a.setPreferredWidth(100);
        a.setCellRenderer(new CustomTableCellRenderer());
        a = jTable1.getColumnModel().getColumn(4);
        a.setPreferredWidth(70);
        a.setCellRenderer(new CustomTableCellRenderer());
        a = jTable1.getColumnModel().getColumn(5);
        a.setPreferredWidth(150);
        a.setCellRenderer(new CustomTableCellRenderer());
        a = jTable1.getColumnModel().getColumn(6);
        a.setPreferredWidth(100);
        a.setCellRenderer(new CustomTableCellRenderer());
        a = jTable1.getColumnModel().getColumn(7);
        a.setPreferredWidth(130);
        a.setCellRenderer(new CustomTableCellRenderer());
        a = jTable1.getColumnModel().getColumn(8);
        a.setPreferredWidth(80);
        a.setCellRenderer(new CustomTableCellRenderer());
        a = jTable1.getColumnModel().getColumn(9);
        a.setPreferredWidth(150);
        a.setCellRenderer(new CustomTableCellRenderer());
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        java.net.URL url = ClassLoader.getSystemResource("kboxviewer/images/kbox.png");
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(url);
        this.setIconImage(img);
    }
    
    private void addRows(String ticketID, String title, String created, String modified, String dueDate, String requestType, String classification, String owner, String status, String reason) {
        model = (DefaultTableModel) jTable1.getModel();
        if(!status.equalsIgnoreCase("Pending")) {
            reason = "";
        }
        // Add the rows of the table
        model.addRow(new Object[]{ticketID, title, created, modified, dueDate, requestType, classification, owner, status, reason});  
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refresh() {
        String url = "jdbc:mysql://"+hostname+":"+port+"/";
        String db = "ORG1";
        String driver = "com.mysql.jdbc.Driver";
        String user = "R1";
        String pass = "password";
        selectedTicketNumber = "";
        try {
            jTable1.clearSelection();
            model = (DefaultTableModel) jTable1.getModel();
            // Remove all contents of the table
            model.getDataVector().removeAllElements();
	    try (BufferedReader br = new BufferedReader(new FileReader(jTextField1.getText()))) {
	        StringBuilder sb = new StringBuilder();
	        String line = br.readLine();
	
	        while (line != null) {
	        		if(sb.length()!=0) {
	        			sb.append(",");
	        		}
	                        sb.append("'").append(line).append("'");
	            line = br.readLine();
	        }
	        String condition = sb.toString();
                
                if( !condition.equalsIgnoreCase("")) {
                    Class.forName(driver);
                    Connection conn;
                    conn = DriverManager.getConnection(url + db, user, pass);
                    for( SQLWarning warn = conn.getWarnings(); warn != null; warn = warn.getNextWarning() ) {
                            System.out.println( "SQL Warning:" ) ;
                            System.out.println( "State  : " + warn.getSQLState()  ) ;
                            System.out.println( "Message: " + warn.getMessage()   ) ;
                            System.out.println( "Error  : " + warn.getErrorCode() ) ;
                    }
                    try (Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery( "SELECT a.ID, a.TITLE, a.CREATED, a.MODIFIED, a.DUE_DATE, a.CUSTOM_FIELD_VALUE6, a.CUSTOM_FIELD_VALUE2, c.FULL_NAME, b.NAME, a.CUSTOM_FIELD_VALUE13, a.CUSTOM_FIELD_VALUE2"+
                                                                                                                                                    " FROM HD_TICKET a" +
                                                                                                                                                    " INNER JOIN HD_STATUS b ON a.HD_STATUS_ID = b.ID" +
                                                                                                                                                    " INNER JOIN USER c ON a.OWNER_ID = c.ID" +
                                                                                                                                                    " WHERE a.ID IN ("+condition+")" )) {
                        int recordCount = 0;
                        // Loop through the result set
                        while( rs.next() ) {
                            addRows(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10));
                            recordCount++;
                        }

                        // Required for MS SQL Server
                        stmt.cancel();
                        stmt.close();
                        rs.close();
                        if(recordCount==0) {
                            JOptionPane.showMessageDialog(null, "Your tickets file does not contain any valid tickets or is empty", "Warning", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                    conn.close();
                }
                else {
                    addRows("","","","","","","","","","");
                    JOptionPane.showMessageDialog(null, "Your tickets file does not contain any valid tickets or is empty", "Warning", JOptionPane.WARNING_MESSAGE);
                }
	    }
            catch(FileNotFoundException fnf) {
                JOptionPane.showMessageDialog(null, fnf, "File not found", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(IOException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(null, "KBOX Viewer v1.0\nby Glenn Dimaliwat\nCopyright 2013", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Runtime.getRuntime().exec("notepad.exe " + jTextField1.getText());
        }
        catch(FileNotFoundException fnf) {
            JOptionPane.showMessageDialog(null, fnf, "File not found", JOptionPane.ERROR_MESSAGE);
        }
        catch(IOException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(null, "1. Click Edit File\n2. Notepad will open the file path indicated in the text box\n3. If the file does not exist, you will be prompted to create a new file, click Yes\n4. Type your ticket numbers separated by a new line (enter)\n5. Go to File and click Save. Close the notepad\n6. Click Refresh", "How to use this App", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        toggleCellMode();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void toggleCellMode() {
        if(jToggleButton1.isSelected()) {
            jTable1.setCellSelectionEnabled(true);
        }
        else {
            jTable1.setCellSelectionEnabled(false);
            jTable1.setRowSelectionAllowed(true);
        }
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.rowAtPoint(new Point(evt.getX(), evt.getY()));
        selectedTicketNumber = (String) jTable1.getModel().getValueAt(row, 0);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if(!selectedTicketNumber.equalsIgnoreCase("")) {
            try {
                URI uri = new URI("http://"+hostname+"/userui/ticket?ID="+selectedTicketNumber);
                Desktop dt = Desktop.getDesktop();
                dt.browse(uri);
                
            } catch ( URISyntaxException | IOException e ) {
                JOptionPane.showMessageDialog(null, "Unable to connect to URL.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a ticket number from the list.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        String lastSearchKey = searchKey;
        try {
            searchKey = "";
            searchKey = JOptionPane.showInputDialog("Find What", lastSearchKey);
            searchKey = searchKey.toLowerCase();
            
            if(!searchKey.equalsIgnoreCase("") && model!=null) {
                for(int x=0;x<=model.getRowCount()-1;x++) {
                    if(model.getValueAt(x, 0).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(0, 0);
                        break;
                    }
                    else if(model.getValueAt(x, 1).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(1, 1);
                        break;
                    }
                    else if(model.getValueAt(x, 2).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(2, 2);
                        break;
                    }
                    else if(model.getValueAt(x, 3).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(3, 3);
                        break;
                    }
                    else if(model.getValueAt(x, 4).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(4, 4);
                        break;
                    }
                    else if(model.getValueAt(x, 5).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(5, 5);
                        break;
                    }
                    else if(model.getValueAt(x, 6).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(6, 6);
                        break;
                    }
                    else if(model.getValueAt(x, 7).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(7, 7);
                        break;
                    }
                    else if(model.getValueAt(x, 8).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(8, 8);
                        break;
                    }
                    else if(model.getValueAt(x, 9).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(9, 9);
                        break;
                    }
                    
                    if(x==model.getRowCount()-1) {
                        JOptionPane.showMessageDialog(null, "Search string not found.", "Information", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                jTable1.requestFocus();
            }
        }
        catch(NullPointerException e) {
            searchKey = lastSearchKey;
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        int searchRow = 0;
        int lastRowSearched = 0;
        try {            
            System.out.println(lastRowSearched);
            System.out.println(jTable1.getSelectedRow());
            if(repeatSearch) {
                searchRow = 0;
            }
            else {
                searchRow = jTable1.getSelectedRow();
                if(searchRow==model.getRowCount()-1) {
                    searchRow = 0;
                }
                else {
                    searchRow = searchRow + 1;
                }
            }
            
            if(!searchKey.equalsIgnoreCase("") && model!=null) {
                for(int x=searchRow;x<=model.getRowCount()-1;x++) {
                    if(model.getValueAt(x, 0).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(0, 0);
                        lastRowSearched = x;
                        break;
                    }
                    else if(model.getValueAt(x, 1).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(1, 1);
                        lastRowSearched = x;
                        break;
                    }
                    else if(model.getValueAt(x, 2).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(2, 2);
                        lastRowSearched = x;
                        break;
                    }
                    else if(model.getValueAt(x, 3).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(3, 3);
                        lastRowSearched = x;
                        break;
                    }
                    else if(model.getValueAt(x, 4).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(4, 4);
                        lastRowSearched = x;
                        break;
                    }
                    else if(model.getValueAt(x, 5).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(5, 5);
                        lastRowSearched = x;
                        break;
                    }
                    else if(model.getValueAt(x, 6).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(6, 6);
                        lastRowSearched = x;
                        break;
                    }
                    else if(model.getValueAt(x, 7).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(7, 7);
                        lastRowSearched = x;
                        break;
                    }
                    else if(model.getValueAt(x, 8).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(8, 8);
                        lastRowSearched = x;
                        break;
                    }
                    else if(model.getValueAt(x, 9).toString().toLowerCase().contains(searchKey)) {
                        jTable1.setRowSelectionInterval(x, x);
                        jTable1.setColumnSelectionInterval(9, 9);
                        lastRowSearched = x;
                        break;
                    }
                }
                
                for(int x=lastRowSearched;x<=model.getRowCount()-1;x++) {
                    for(int y=0;y<=model.getColumnCount()-1;y++) {
                        if(model.getValueAt(x, y).toString().toLowerCase().contains(searchKey)) {
                            if(lastRowSearched==x) {
                                repeatSearch = true;
                            }
                            else {
                                repeatSearch = false;
                            }
                            break;
                        }
                    }
                }
                
                jTable1.requestFocus();
            }
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        refresh();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jToggleButton1.doClick();
        toggleCellMode();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the look and feel */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KBOXJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}

